"""Generates the C++ gains header from the Python source of truth.

Values are SIM-derived (LQR from the linearized plant design, PID defaults are placeholders),
NOT tuned or validated for the real robot. PID sign/stability untested (#359). No default
output path. Every value is quantized to float32 first.
"""

import argparse
import hashlib
import math
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hal.hal import HAL_CONTRACT_VERSION


SCHEMA = 1


def f32(x):
    """Quantize x to float32 by packing/unpacking with struct.

    Raises ValueError if x is not finite or if packing overflows.
    """
    if not math.isfinite(x):
        raise ValueError(f"Value {x} is not finite")
    try:
        return struct.unpack('<f', struct.pack('<f', x))[0]
    except OverflowError as e:
        raise ValueError(f"Packing {x} to float32 overflowed") from e


def fmt_f32(x):
    """Format x as a C++ float literal after quantizing to float32.

    Returns a string like '1.0f', '0.0f', '-0.125f'.
    """
    v = f32(x)
    s = '%.9g' % v
    if not any(c in s for c in '.en'):
        s += '.0'
    return s + 'f'


def canonical_text(K, theta_ref, out_limit, pid, contract_version):
    """Return canonical text representation for hashing.

    K is a 2-sequence, pid is (kp, ki, kd, pid_out_limit).
    Every number is rendered as '%.9g' % f32(v).
    Returns exactly formatted string.
    """
    k0 = '%.9g' % f32(K[0])
    k1 = '%.9g' % f32(K[1])
    t = '%.9g' % f32(theta_ref)
    o = '%.9g' % f32(out_limit)
    kp = '%.9g' % f32(pid[0])
    ki = '%.9g' % f32(pid[1])
    kd = '%.9g' % f32(pid[2])
    pl = '%.9g' % f32(pid[3])
    return f"schema={SCHEMA}\ncontract_version={int(contract_version)}\nK={k0},{k1}\ntheta_ref={t}\nout_limit={o}\npid={kp},{ki},{kd},{pl}\n"


def gains_hash(K, theta_ref, out_limit, pid, contract_version):
    """Return SHA256 hash of canonical_text as an int.

    Uses first 8 hex digits of the SHA256.
    """
    text = canonical_text(K, theta_ref, out_limit, pid, contract_version)
    return int(hashlib.sha256(text.encode('ascii')).hexdigest()[:8], 16)


def format_hash(h):
    """Format hash as '0x%08x' % h (lowercase)."""
    return '0x%08x' % h


def render_header(K, theta_ref, out_limit, pid, contract_version):
    """Render the C++ gains header.

    Returns the complete header text with trailing newline.
    K and pid inputs are quantized to f32 first.
    """
    k0 = f32(K[0])
    k1 = f32(K[1])
    t = f32(theta_ref)
    o = f32(out_limit)
    kp = f32(pid[0])
    ki = f32(pid[1])
    kd = f32(pid[2])
    pl = f32(pid[3])
    h = gains_hash(K, theta_ref, out_limit, pid, contract_version)

    lines = [
        "// GENERATED by freecad-workspace export_cpp.py -- do not edit.",
        "// SIM-derived design values (LQR from the linearized plant model). Not tuned or validated for the real robot.",
        "#pragma once",
        "#include <cstdint>",
        "namespace balance_gains {",
        f"constexpr uint32_t kSchema = {SCHEMA};",
        f"constexpr uint32_t kContractVersion = {int(contract_version)};",
        f"constexpr uint32_t kGainsHash = {format_hash(h)}u;",
        f"constexpr float kLqrK[2] = {{ {fmt_f32(k0)}, {fmt_f32(k1)} }};    // [theta, theta_dot]",
        f"constexpr float kThetaRefRad = {fmt_f32(t)};",
        f"constexpr float kOutLimit = {fmt_f32(o)};",
        f"constexpr float kPidKp = {fmt_f32(kp)}, kPidKi = {fmt_f32(ki)}, kPidKd = {fmt_f32(kd)}, kPidOutLimit = {fmt_f32(pl)};",
        "}  // namespace balance_gains",
    ]
    return '\n'.join(lines) + '\n'


def default_gains():
    """Return dict of default gains, all quantized to float32.

    Lazily imports from hal.control_core.
    Dict keys match render_header/gains_hash parameter names.
    """
    from hal.control_core import (
        LqrBalance,
        DEFAULT_THETA_REF_RAD,
        DEFAULT_OUT_LIMIT,
        DEFAULT_PID_KP,
        DEFAULT_PID_KI,
        DEFAULT_PID_KD,
    )

    lqr = LqrBalance()
    K = lqr.K

    return {
        "K": (f32(K[0]), f32(K[1])),
        "theta_ref": f32(DEFAULT_THETA_REF_RAD),
        "out_limit": f32(DEFAULT_OUT_LIMIT),
        "pid": (f32(DEFAULT_PID_KP), f32(DEFAULT_PID_KI), f32(DEFAULT_PID_KD), f32(DEFAULT_OUT_LIMIT)),
        "contract_version": HAL_CONTRACT_VERSION,
    }


def main(argv=None):
    """Main entry point.

    Requires --out PATH; writes header to PATH; prints path and hash; returns 0.
    """
    parser = argparse.ArgumentParser(
        description="Generate C++ gains header from Python source of truth"
    )
    parser.add_argument("--out", required=True, help="Output file path")
    args = parser.parse_args(argv)

    gains = default_gains()
    header_text = render_header(**gains)
    h = gains_hash(**gains)

    path = Path(args.out)
    with open(path, 'w', newline='\n', encoding='ascii') as f:
        f.write(header_text)

    print(path)
    print(format_hash(h))

    return 0


__all__ = [
    "SCHEMA",
    "f32",
    "fmt_f32",
    "canonical_text",
    "gains_hash",
    "format_hash",
    "render_header",
    "default_gains",
    "main",
]


if __name__ == "__main__":
    sys.exit(main())
