#!/usr/bin/env python3
"""
Stage 3 — minimal wheel articulation sanity check.

A Webots robot controller (Python, `controller` module — the Webots
runtime's own Python, not the pendulum-tools mamba env) for the
turtlebot3_poc PROTO/world generated by urdf2webots from
urdf/turtlebot3_poc.urdf.

This is deliberately NOT a real control loop: it commands both wheel
motors to a fixed velocity, steps the simulation a handful of times, reads
back each wheel joint's resulting position/velocity, and prints a
pass/fail verdict. Its only job is to prove articulation (the continuous
wheel joints defined in the URDF actually move under Motor commands once
imported into Webots) — nothing more.

Device names below assume urdf2webots's default HingeJoint/motor naming,
which mirrors the URDF joint names (wheel_left_joint / wheel_right_joint).
If the generated PROTO uses different device names, this script's device
lookup will fail loudly and the actual names/errors were logged to
webots/run_batch.log for FINDINGS.md.
"""

import sys

from controller import Robot

TIME_STEP_MS = 32
TARGET_VELOCITY_RAD_S = 2.0
SIM_STEPS = 20

WHEEL_MOTOR_NAMES = ["wheel_left_joint", "wheel_right_joint"]
# Fallback names urdf2webots has been observed to use in some versions.
WHEEL_MOTOR_NAME_FALLBACKS = [
    ["wheel_left_joint_motor", "wheel_right_joint_motor"],
    ["left_wheel_motor", "right_wheel_motor"],
]


def main() -> int:
    robot = Robot()

    all_name_sets = [WHEEL_MOTOR_NAMES] + WHEEL_MOTOR_NAME_FALLBACKS

    left_name, left_motor = None, None
    right_name, right_motor = None, None
    for names in all_name_sets:
        if left_motor is None:
            left_name, left_motor = names[0], robot.getDevice(names[0])
        if right_motor is None:
            right_name, right_motor = names[1], robot.getDevice(names[1])

    if left_motor is None or right_motor is None:
        print("FAIL: could not find wheel motor devices.")
        print(f"  Tried left names in: {[n[0] for n in all_name_sets]}")
        print(f"  Tried right names in: {[n[1] for n in all_name_sets]}")
        return 1

    print(f"Found left motor device:  {left_name}")
    print(f"Found right motor device: {right_name}")

    # Position sensors (if the PROTO exposes them) let us confirm actual
    # rotation, not just that the velocity command was accepted.
    left_sensor = robot.getDevice(f"{left_name}_sensor") or robot.getDevice("wheel_left_joint_sensor")
    right_sensor = robot.getDevice(f"{right_name}_sensor") or robot.getDevice("wheel_right_joint_sensor")
    if left_sensor:
        left_sensor.enable(TIME_STEP_MS)
    if right_sensor:
        right_sensor.enable(TIME_STEP_MS)

    # Continuous joints in Webots RotationalMotor: set position to +inf to
    # allow velocity-only control.
    left_motor.setPosition(float("inf"))
    right_motor.setPosition(float("inf"))
    left_motor.setVelocity(TARGET_VELOCITY_RAD_S)
    right_motor.setVelocity(TARGET_VELOCITY_RAD_S)

    initial_left = left_sensor.getValue() if left_sensor else None
    initial_right = right_sensor.getValue() if right_sensor else None

    step_count = 0
    while robot.step(TIME_STEP_MS) != -1 and step_count < SIM_STEPS:
        step_count += 1

    final_left = left_sensor.getValue() if left_sensor else None
    final_right = right_sensor.getValue() if right_sensor else None

    print(f"\nRan {step_count} simulation steps at {TIME_STEP_MS}ms each "
          f"({step_count * TIME_STEP_MS / 1000.0:.2f}s simulated).")
    print(f"Commanded velocity: {TARGET_VELOCITY_RAD_S} rad/s on both wheels.")

    result_ok = True
    if left_sensor and right_sensor:
        delta_left = final_left - initial_left
        delta_right = final_right - initial_right
        print(f"Left wheel joint position:  {initial_left:.4f} -> {final_left:.4f} rad (delta {delta_left:.4f})")
        print(f"Right wheel joint position: {initial_right:.4f} -> {final_right:.4f} rad (delta {delta_right:.4f})")

        if abs(delta_left) < 1e-4 or abs(delta_right) < 1e-4:
            print("FAIL: wheel joint position did not change under commanded velocity.")
            result_ok = False
        else:
            print("PASS: both wheel joints rotated under commanded velocity.")
    else:
        print("WARN: no position sensor devices found on the wheel joints — "
              "cannot directly confirm rotation, only that setVelocity() was "
              "accepted without error. Treating as inconclusive, not PASS.")
        result_ok = False

    print(f"\nVERDICT: {'PASS' if result_ok else 'FAIL/INCONCLUSIVE'}")
    return 0 if result_ok else 1


if __name__ == "__main__":
    sys.exit(main())
