#!/usr/bin/env python3
"""
Stage 3 — minimal wheel articulation sanity check.

A Webots robot controller (Python, `controller` module — the Webots
runtime's own Python, not the pendulum-tools mamba env) for the
turtlebot3_poc PROTO/world generated by urdf2webots from
urdf/turtlebot3_poc.urdf.

This is deliberately NOT a real control loop: it commands both wheel
motors to a fixed velocity, steps the simulation for a bounded duration
(long enough to be watchable in the GUI, ~10s — see issue #26), printing
periodic wheel position/velocity telemetry along the way, reads back each
wheel joint's final position/velocity, and prints a pass/fail verdict. Its
only job is to prove articulation (the continuous wheel joints defined in
the URDF actually move under Motor commands once imported into Webots) —
nothing more. The PASS/FAIL verdict logic and exit-code contract are
unchanged from the original ~0.64s version (issue #24) — only the step
count and the addition of periodic prints are new (issue #26); anything
scripting against "VERDICT: PASS"/exit code 0 still works unmodified.

Device names below assume urdf2webots's default HingeJoint/motor naming,
which mirrors the URDF joint names (wheel_left_joint / wheel_right_joint).
If the generated PROTO uses different device names, this script's device
lookup will fail loudly and the actual names/errors were logged to
webots/run_batch.log for FINDINGS.md.
"""

import sys

from controller import Supervisor

TIME_STEP_MS = 32
TARGET_VELOCITY_RAD_S = 2.0
# ~10s simulated at 32ms/step (issue #26 — long enough for a GUI-watching
# human to see ongoing motion/telemetry, not just a ~0.64s blip). The
# PASS/FAIL verdict logic below is unchanged from the original 20-step
# version — it's simply evaluated at this later step count.
SIM_STEPS = 300
# Print wheel telemetry every this many steps so a GUI-watching human sees
# periodic confirmation the sim is alive, rather than silence until the
# final verdict.
PRINT_EVERY_STEPS = 25

WHEEL_MOTOR_NAMES = ["wheel_left_joint", "wheel_right_joint"]
# Fallback names urdf2webots has been observed to use in some versions.
WHEEL_MOTOR_NAME_FALLBACKS = [
    ["wheel_left_joint_motor", "wheel_right_joint_motor"],
    ["left_wheel_motor", "right_wheel_motor"],
]


def main() -> int:
    # Supervisor is a Robot subclass (issue #32) — all existing Motor/
    # PositionSensor code below keeps working unchanged; the only reason
    # for the upgrade is getSelf()/getPosition() below, to directly
    # confirm chassis translation (not just wheel-angle rotation).
    robot = Supervisor()

    all_name_sets = [WHEEL_MOTOR_NAMES] + WHEEL_MOTOR_NAME_FALLBACKS

    left_name, left_motor = None, None
    right_name, right_motor = None, None
    for names in all_name_sets:
        if left_motor is None:
            left_name, left_motor = names[0], robot.getDevice(names[0])
        if right_motor is None:
            right_name, right_motor = names[1], robot.getDevice(names[1])

    if left_motor is None or right_motor is None:
        print("FAIL: could not find wheel motor devices.")
        print(f"  Tried left names in: {[n[0] for n in all_name_sets]}")
        print(f"  Tried right names in: {[n[1] for n in all_name_sets]}")
        return 1

    print(f"Found left motor device:  {left_name}")
    print(f"Found right motor device: {right_name}")

    # Position sensors (if the PROTO exposes them) let us confirm actual
    # rotation, not just that the velocity command was accepted.
    left_sensor = robot.getDevice(f"{left_name}_sensor") or robot.getDevice("wheel_left_joint_sensor")
    right_sensor = robot.getDevice(f"{right_name}_sensor") or robot.getDevice("wheel_right_joint_sensor")
    if left_sensor:
        left_sensor.enable(TIME_STEP_MS)
    if right_sensor:
        right_sensor.enable(TIME_STEP_MS)

    # Continuous joints in Webots RotationalMotor: set position to +inf to
    # allow velocity-only control.
    left_motor.setPosition(float("inf"))
    right_motor.setPosition(float("inf"))
    left_motor.setVelocity(TARGET_VELOCITY_RAD_S)
    right_motor.setVelocity(TARGET_VELOCITY_RAD_S)

    # A PositionSensor's value is NaN until the simulation has advanced at
    # least one time step past enable() (a minor but easy-to-hit Webots
    # quirk — see FINDINGS.md), so take the "initial" reading after step 1,
    # not before any step.
    robot.step(TIME_STEP_MS)
    initial_left = left_sensor.getValue() if left_sensor else None
    initial_right = right_sensor.getValue() if right_sensor else None

    # Chassis global position (issue #32) — the wheel-angle check alone
    # cannot distinguish "chassis actually translated" from "wheels spun
    # in place because the chassis got welded to the static world" (the
    # base_footprint root-link bug). getSelf() returns this Robot node
    # itself (requires `supervisor TRUE` on the PROTO instance in the
    # .wbt world file).
    self_node = robot.getSelf()
    initial_position = self_node.getPosition()

    # Observed angular velocity is computed from the position-sensor delta
    # since the previous print, not read via Motor.getVelocity() — that API
    # returns the last *commanded target* velocity (set once above via
    # setVelocity() and never changed), not a measured/live value, so it
    # would always print the same constant 2.0000 rad/s and misleadingly
    # imply live confirmation when only the position field is actually live.
    step_count = 1
    prev_print_left = initial_left
    prev_print_right = initial_right
    # Baseline is taken after the pre-loop warm-up step (step_count == 1,
    # the earliest point a position-sensor reading is valid — see above),
    # not before any step. Since the loop below only prints every
    # PRINT_EVERY_STEPS steps, this means the FIRST printed observed_vel
    # covers PRINT_EVERY_STEPS - 1 steps, not a full PRINT_EVERY_STEPS —
    # every later print covers a full PRINT_EVERY_STEPS-step interval
    # (delta against the *previous print*, not against this baseline).
    # dt_s below is always computed from the actual elapsed time, so the
    # printed observed_vel is correct either way — this is a cosmetic
    # off-by-one in the first interval's width only, not a bug (review
    # finding #8, round 3).
    prev_print_elapsed_s = step_count * TIME_STEP_MS / 1000.0

    while robot.step(TIME_STEP_MS) != -1 and step_count < SIM_STEPS:
        step_count += 1
        if step_count % PRINT_EVERY_STEPS == 0:
            elapsed_s = step_count * TIME_STEP_MS / 1000.0
            left_pos = left_sensor.getValue() if left_sensor else float("nan")
            right_pos = right_sensor.getValue() if right_sensor else float("nan")
            dt_s = elapsed_s - prev_print_elapsed_s
            left_obs_vel = (left_pos - prev_print_left) / dt_s if left_sensor and dt_s > 0 else float("nan")
            right_obs_vel = (right_pos - prev_print_right) / dt_s if right_sensor and dt_s > 0 else float("nan")
            print(f"  t={elapsed_s:5.2f}s step={step_count:3d}  "
                  f"left pos={left_pos:.4f} rad observed_vel={left_obs_vel:.4f} rad/s  |  "
                  f"right pos={right_pos:.4f} rad observed_vel={right_obs_vel:.4f} rad/s")
            prev_print_left, prev_print_right, prev_print_elapsed_s = left_pos, right_pos, elapsed_s

    final_left = left_sensor.getValue() if left_sensor else None
    final_right = right_sensor.getValue() if right_sensor else None
    final_position = self_node.getPosition()

    print(f"\nRan {step_count} simulation steps at {TIME_STEP_MS}ms each "
          f"({step_count * TIME_STEP_MS / 1000.0:.2f}s simulated).")
    print(f"Commanded velocity: {TARGET_VELOCITY_RAD_S} rad/s on both wheels.")

    dx = final_position[0] - initial_position[0]
    dy = final_position[1] - initial_position[1]
    print(f"Chassis position: {initial_position} -> {final_position} (dx={dx:.4f}, dy={dy:.4f})")

    wheels_rotated = False
    result_ok = True
    if left_sensor and right_sensor:
        delta_left = final_left - initial_left
        delta_right = final_right - initial_right
        print(f"Left wheel joint position:  {initial_left:.4f} -> {final_left:.4f} rad (delta {delta_left:.4f})")
        print(f"Right wheel joint position: {initial_right:.4f} -> {final_right:.4f} rad (delta {delta_right:.4f})")

        if abs(delta_left) < 1e-4 or abs(delta_right) < 1e-4:
            print("FAIL: wheel joint position did not change under commanded velocity.")
            result_ok = False
        else:
            wheels_rotated = True
            print("PASS: both wheel joints rotated under commanded velocity.")
    else:
        print("WARN: no position sensor devices found on the wheel joints — "
              "cannot directly confirm rotation, only that setVelocity() was "
              "accepted without error. Treating as inconclusive, not PASS.")
        result_ok = False

    # Chassis displacement check (issue #32) — required IN ADDITION to the
    # wheel-angle check above, not instead of it. This is what actually
    # catches the base_footprint root-link bug: with that bug, the wheel
    # joints rotate normally (PASS above) but the chassis stays welded to
    # the static world (dx == dy == 0), which the wheel-angle check alone
    # could never detect.
    chassis_moved = abs(dx) > 1e-3 or abs(dy) > 1e-3
    if not chassis_moved:
        if wheels_rotated:
            print("FAIL: wheels rotated but chassis did not translate "
                  "(dx/dy both below 1e-3) — the robot is likely welded "
                  "to the static world (see issue #32).")
        else:
            print("FAIL: chassis did not translate (dx/dy both below 1e-3).")
    else:
        print("PASS: chassis translated under commanded wheel velocity.")

    result_ok = result_ok and chassis_moved

    print(f"\nVERDICT: {'PASS' if result_ok else 'FAIL/INCONCLUSIVE'}")
    return 0 if result_ok else 1


if __name__ == "__main__":
    sys.exit(main())
